library(patchwork)
library(cluster)
library(cowplot)
library(Rtsne)
library(scatterplot3d)
library(plotly)
library(ggsci)
library(ggrepel)
library(ggiraph)
library(gplots)
library(ggridges)
library(ggstance)
library(autoplotly)
library(RColorBrewer)
library(pheatmap)
library(treemap)
library(FateID)
library(sigora)
library(colorpatch)
library(Seurat)
library(tidyverse)
library(reticulate)
library(ggbeeswarm)
library(ggrepel)
library(ggridges)
library(RColorBrewer)
library(devtools)
library(ggplot2)
library(dplyr)
library(Matrix)
library(umap)
library(rhdf5)
library(scCustomize)
library(patchwork)
library(viridis)
library(Nebulosa)
library(sctransform)

setwd("~/Desktop/lanser_nucseq/hpa_rds_files")

#Load objects
HPA_PBS <- readRDS("HPA_PBS_filtered.rds")
WT_KO <- readRDS("WT_KO_merged_postUMAP_filtered.rds")

all <- merge(HPA_PBS, WT_KO)

all <- SCTransform(all, method = "glmGamPoi", vars.to.regress = "percent.mt")
###PCA
all <- RunPCA(object = all)
ElbowPlot(object = all, ndims = 50)
###
all <- FindNeighbors(object = all, dims = 1:40)
all <- FindClusters(object = all, resolution = 1.2)
all <- RunUMAP(all, dims = 1:40)
DimPlot_scCustom(all, label = T)
FeaturePlot_scCustom(all, features = "Dlgap1", label = T)


saveRDS(all, "allCells_filtered.rds")

